/*
 * Copyright 2002-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
	alias(libs.plugins.spring.boot)
	id 'java'
	id 'checkstyle'
	alias(libs.plugins.spring.javaformat)
}

group = 'org.springframework.cloud'
version = '0.0.1.BUILD-SNAPSHOT'

base {
	archivesName = 'bookstore-service-broker'
}

java {
	sourceCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
	options.compilerArgs = [
			"-Xlint:serial",
			"-Xlint:varargs",
			"-Xlint:cast",
			"-Xlint:classfile",
			"-Xlint:dep-ann",
			"-Xlint:divzero",
			"-Xlint:empty",
			"-Xlint:finally",
			"-Xlint:overrides",
			"-Xlint:path",
			"-Xlint:-processing",
			"-Xlint:static",
			"-Xlint:try",
			"-Xlint:fallthrough",
			"-Xlint:rawtypes",
			"-Xlint:deprecation",
			"-Xlint:unchecked",
			"-Xlint:options",
			"-Werror",
			"-parameters"
	]
}

repositories {
	mavenCentral()
}

dependencies {
	checkstyle(libs.spring.javaformat.checkstyle)
	implementation platform(libs.spring.boot.dependencies)
	developmentOnly platform(libs.spring.boot.dependencies)
	implementation(libs.spring.cloud.starter.open.service.broker)
	implementation('org.springframework.boot:spring-boot-starter-webflux')
	implementation('org.springframework.boot:spring-boot-starter-actuator')
	implementation('org.springframework.boot:spring-boot-starter-security')
	implementation('org.springframework.boot:spring-boot-starter-data-mongodb-reactive')
	implementation('org.springframework.hateoas:spring-hateoas')
	developmentOnly('org.springframework.boot:spring-boot-devtools')
	developmentOnly('org.springframework.boot:spring-boot-docker-compose')
	testImplementation('org.springframework.boot:spring-boot-starter-webflux-test')
	testImplementation('org.springframework.boot:spring-boot-starter-data-mongodb-reactive-test')
	testImplementation('org.springframework.boot:spring-boot-testcontainers')
	testImplementation('org.springframework.security:spring-security-test')
	testImplementation('org.testcontainers:testcontainers-junit-jupiter')
	testImplementation('org.testcontainers:testcontainers-mongodb')
	testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

checkstyle {
	showViolations = true
}
tasks.named('checkstyleTest') {
	configFile = configDirectory.get().file("checkstyle-test.xml").asFile
}

tasks.named('test') {
	useJUnitPlatform()
}

wrapper {
	gradleVersion = '9.7.1'
}

if (!project.hasProperty("dockerGroup")) {
	ext.dockerGroup = "sample"
}

tasks.named('bootBuildImage') {
	imageName = "${dockerGroup}/bookstore-service-broker:${version}"
}
