= Overview

This project implements a sample service broker that adheres to the https://www.openservicebrokerapi.org/[Open Service Broker API] using the https://cloud.spring.io/spring-cloud-open-service-broker/[Spring Cloud Open Service Broker] framework. It can be deployed to either Cloud Foundry or Kubernetes, and can be registered as a service broker to either platform.

== Compatibility

* https://projects.spring.io/spring-framework/[Spring Framework] 5.2.x
* https://projects.spring.io/spring-boot/[Spring Boot] 2.2.x
* https://cloud.spring.io/spring-cloud-open-service-broker/[Spring Cloud Open Service Broker] 3.1.x

== Getting Started

This service broker manages instances of a bookstore service.

When a service instance is https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#provisioning[provisioned], a new data structure is allocated in memory.

When a https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#credentials[service binding] is created, a URL and basic auth credentials are provided in the binding credentials. The bookstore URL and credentials can be used to add, retrieve, delete, and list books in the bookstore. Unique credentials are generated for each service binding.

== Build

This project requires Java 8 at a minimum. 

The project is built with Gradle. The https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle wrapper] allows you to build the project on multiple platforms and even if you do not have Gradle installed; run it in place of the `gradle` command (as `./gradlew`) from the root of the main project directory.

=== To compile the project and run tests

    ./gradlew build

== Deploy

Once the project is built, it can be deployed and registered to either Cloud Foundry or Kubernetes.

* link:deploy/cloudfoundry/README.adoc[deploy to Cloud Foundry]
* link:deploy/kubernetes/README.adoc[deploy to Kubernetes]
